version: "3.9"
services:
  geoapp:
    container_name: geologicApp
    build:
      context: .
      dockerfile: dockerfileApp
    environment:
      spring.datasource.url: jdbc:postgresql://serverdb:5432/GeologicalData
    depends_on:
      - serverdb
    ports:
      - "8080:8080"
    networks:
      - postgres
    command: bash -c "java -jar taskGeological.jar"
    restart: on-failure
  serverdb:
    container_name: GeologicalDB
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpwd
      POSTGRES_DB: GeologicalData
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: on-failure
  monitordb:
    container_name: pgAdmin
    image: dpage/pgadmin4:6.20
    environment:
      PGADMIN_DEFAULT_EMAIL: ewro01@ya.ru
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "9991:80"
    networks:
      - postgres
    restart: on-failure

networks:
  postgres:
    driver: bridge